In [1]:
import os, re, glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
groups_folder_path = './2. Jointed_Datasets_without_background/'
categories = ['2. Lier', '3. Sitter', '4. Taxier', '5. Blocker']
num_classes = len(categories)

In [3]:
image_w = 500
image_h = 500

X = []
Y = []
  
for idex, categorie in enumerate(categories):
    label = [0 for i in range(num_classes)]
    label[idex] = 1
    image_dir = groups_folder_path + categorie + '/'
  
    for top, dir, f in os.walk(image_dir):
        for filename in f:
            print(image_dir+filename)
            img = cv2.imread(image_dir+filename)
            img = cv2.resize(img, None, fx=image_w/img.shape[1], fy=image_h/img.shape[0])
            X.append(img/256)
            Y.append(label)
            
X = np.array(X)
Y = np.array(Y)
 
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)
xy = (X_train, X_test, Y_train, Y_test)
 
np.save("./3. img_data/img_data.npy", xy)

./2. Jointed_Datasets_without_background/2. Lier/lier_0001.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0004.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0006.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0007.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0008.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0009.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0010.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0011.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0012.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0013.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0014.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0015.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0016.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0017.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0018.jpg
./2. Jointed_Datasets_without_background/2. Lier/lier_0

./2. Jointed_Datasets_without_background/4. Taxier/taxier_0056.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0057.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0058.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0059.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0060.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0061.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0062.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0063.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0064.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0065.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0066.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0067.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0068.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0069.jpg
./2. Jointed_Datasets_without_background/4. Taxier/taxier_0070

C:\Users\nakhe\Anaconda3\envs\tensor2_gpu\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [4]:
## 먼저 기존의 np.load를 np_load_old에 저장해둠.
np_load_old = np.load

## 기존의 parameter을 바꿔줌
np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, Activation, Dense
from tensorflow.keras.layers import Flatten, Convolution2D, MaxPooling2D
from tensorflow.keras.models import load_model
import cv2
 
X_train, X_test, Y_train, Y_test = np.load('./3. img_data/img_data.npy')

In [6]:
X_train.shape[1:]

(500, 500, 3)

In [7]:
model = Sequential()
model = Sequential()
model.add(Convolution2D(16, 3, 3, activation='relu', input_shape=X_train.shape[1:]))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
  
model.add(Convolution2D(64, 3, 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
 
model.add(Convolution2D(64, 3, 3))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
  
model.add(Flatten())
model.add(Dense(256, activation = 'relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes,activation = 'softmax'))

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 166, 166, 16)      448       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 83, 83, 16)        0         
_________________________________________________________________
dropout (Dropout)            (None, 83, 83, 16)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 27, 27, 64)        9280      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 13, 13, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 64)         

In [9]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [10]:
from tensorflow.keras.callbacks import EarlyStopping

es = EarlyStopping(monitor='val_acc', patience=3)
model.fit(X_train, Y_train, batch_size=32, epochs=50, validation_split = 0.2)

Train on 124 samples, validate on 32 samples
Epoch 1/50
124/124 [==============================] - 10s 81ms/sample - loss: 0.5324 - accuracy: 0.7500 - val_loss: 0.5343 - val_accuracy: 0.7500
Epoch 2/50
124/124 [==============================] - 2s 13ms/sample - loss: 0.4988 - accuracy: 0.7681 - val_loss: 0.5297 - val_accuracy: 0.7500
Epoch 3/50
124/124 [==============================] - 1s 12ms/sample - loss: 0.5030 - accuracy: 0.7560 - val_loss: 0.5326 - val_accuracy: 0.7500
Epoch 4/50
124/124 [==============================] - 1s 12ms/sample - loss: 0.4885 - accuracy: 0.7540 - val_loss: 0.5319 - val_accuracy: 0.7500
Epoch 5/50
124/124 [==============================] - 1s 12ms/sample - loss: 0.5065 - accuracy: 0.7661 - val_loss: 0.5299 - val_accuracy: 0.7500
Epoch 6/50
124/124 [==============================] - 1s 12ms/sample - loss: 0.4949 - accuracy: 0.7601 - val_loss: 0.5322 - val_accuracy: 0.7500
Epoch 7/50
124/124 [==============================] - 1s 12ms/sample - loss: 0.4948 

In [11]:
model.save('Gesture_Detection_Model.h5')

In [12]:
def Dataization(img_path):
    image_w = 500
    image_h = 500
    img = cv2.imread(img_path)
    img = cv2.resize(img, None, fx=image_w/img.shape[1], fy=image_h/img.shape[0])
    return (img/256)

In [13]:
src = []
name = []
test = []
image_dir = "./"
for file in os.listdir(image_dir):
    if (file.find('.jpg') is not -1):      
        src.append(image_dir + file)
        name.append(file)
        test.append(Dataization(image_dir + file))
 
 
test = np.array(test)
model = load_model('Gesture_Detection_Model.h5')
predict = model.predict_classes(test)
predict_prob = model.predict_proba(test)
 
for i in range(len(test)):
    print(name[i] + " : , Predict : "+ str(categories[predict[i]]))

print(predict_prob)

blocker_test.jpg : , Predict : 5. Blocker
blocker_test_back.jpg : , Predict : 5. Blocker
blocker_test_noback.jpg : , Predict : 5. Blocker
sitter_test.jpg : , Predict : 5. Blocker
sitter_test_back.jpg : , Predict : 5. Blocker
sitter_test_noback.jpg : , Predict : 3. Sitter
taxier_test.jpg : , Predict : 5. Blocker
taxier_test_back.jpg : , Predict : 5. Blocker
taxier_test_noback.jpg : , Predict : 2. Lier
[[1.39308140e-01 3.53280399e-07 5.31865544e-06 8.60686183e-01]
 [1.78541001e-02 6.25094998e-08 6.78774086e-07 9.82145190e-01]
 [1.23445041e-01 1.01199448e-01 1.50392741e-01 6.24962687e-01]
 [1.67102443e-12 4.80553455e-04 5.55322510e-10 9.99519467e-01]
 [3.96342160e-12 6.65126741e-02 7.69663515e-08 9.33487177e-01]
 [3.52558983e-03 6.06476545e-01 3.89386803e-01 6.11053954e-04]
 [8.19137087e-04 1.11450959e-07 1.66967395e-09 9.99180734e-01]
 [2.23027333e-03 4.56735494e-09 6.79900025e-11 9.97769713e-01]
 [9.98265684e-01 6.28423277e-06 1.36663875e-05 1.71439757e-03]]
